SUBDIR = src xml
SUBDIR += osapi
C_FILE_LIST = $(wildcard *.c)
#O_FILE_LIST = $(wilecard *.o)
O_FILE_LIST = $(patsubst %.c, %.o, $(C_FILE_LIST))
D_FILE_LIST = $(patsubst %.c, %.d, $(C_FILE_LIST))
APPLIACTION = sort
$(APPLIACTION):sort.o _sort.o 
	gcc $^ -o $(APPLIACTION)

%.o:%.c
	gcc -c -MMD $< -o $@

-include $(D_FILE_LIST)

#sort.o:sort.h

clean:
	rm -rf *.o *.d $(APPLIACTION)

var:
	@echo $(SUBDIR)

wild_card:
	@echo $(C_FILE_LIST)
	@echo $(O_FILE_LIST)

